version: '3.8'

services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: ./server
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=ci

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_HOST=server
      - SHAREIT_PORT=9090